2025-07-10 11:40:09,819 - INFO - Starting container: energy-generator
2025-07-10 11:40:09,819 - INFO - Command: docker run -v /home/work/project/AIEffect-3.1-to-3.2/data:/data aieffect-31-to-32-energy-generator
2025-07-10 11:40:10,384 - INFO - energy-generator STDOUT:
Container 1: Generated 10 records.

2025-07-10 11:40:10,384 - INFO - Starting container: energy-analyzer
2025-07-10 11:40:10,384 - INFO - Command: docker run -v /home/work/project/AIEffect-3.1-to-3.2/data:/data aieffect-31-to-32-energy-analyzer
2025-07-10 11:40:10,885 - INFO - energy-analyzer STDOUT:
[
  {
    "timestamp": "2024-01-15T10:30:00Z",
    "household_id": "H003",
    "power": 2.04,
    "efficiency": 0.135,
    "status": "normal",
    "anomaly_detected": false
  },
  {
    "timestamp": "2024-01-15T10:31:00Z",
    "household_id": "H003",
    "power": 4.07,
    "efficiency": 0.213,
    "status": "normal",
    "anomaly_detected": false
  },
  {
    "timestamp": "2024-01-15T10:32:00Z",
    "household_id": "H002",
    "power": 2.92,
    "efficiency": 0.122,
    "status": "normal",
    "anomaly_detected": false
  },
  {
    "timestamp": "2024-01-15T10:33:00Z",
    "household_id": "H001",
    "power": 3.76,
    "efficiency": 0.308,
    "status": "normal",
    "anomaly_detected": false
  },
  {
    "timestamp": "2024-01-15T10:34:00Z",
    "household_id": "H001",
    "power": 3.17,
    "efficiency": 0.24,
    "status": "normal",
    "anomaly_detected": false
  },
  {
    "timestamp": "2024-01-15T10:35:00Z",
    "household_id": "H002",
    "power": 4.76,
    "efficiency": 0.381,
    "status": "normal",
    "anomaly_detected": false
  },
  {
    "timestamp": "2024-01-15T10:36:00Z",
    "household_id": "H001",
    "power": 2.09,
    "efficiency": 0.097,
    "status": "normal",
    "anomaly_detected": false
  },
  {
    "timestamp": "2024-01-15T10:37:00Z",
    "household_id": "H002",
    "power": 4.57,
    "efficiency": 0.321,
    "status": "normal",
    "anomaly_detected": false
  },
  {
    "timestamp": "2024-01-15T10:38:00Z",
    "household_id": "H003",
    "power": 2.84,
    "efficiency": 0.212,
    "status": "normal",
    "anomaly_detected": false
  },
  {
    "timestamp": "2024-01-15T10:39:00Z",
    "household_id": "H002",
    "power": 4.57,
    "efficiency": 0.241,
    "status": "normal",
    "anomaly_detected": false
  }
]
Container 2: Processed 10 records, and Skipped 0 invalid rows

2025-07-10 11:40:10,886 - INFO - Starting container: report-generator
2025-07-10 11:40:10,886 - INFO - Command: docker run -v /home/work/project/AIEffect-3.1-to-3.2/data:/data aieffect-31-to-32-report-generator
2025-07-10 11:40:11,455 - INFO - report-generator STDOUT:
 Container 3: Report generated with 10 records.

2025-07-10 11:40:11,455 - INFO - All containers executed.
2025-07-25 16:40:00,081 - INFO - [gRPC] Executing energy-generator
2025-07-25 16:40:00,086 - INFO - energy-generator succeeded: Dummy processed /data/energy_data.csv to /data/output1.json
2025-07-25 16:40:00,086 - INFO - [gRPC] Executing energy-analyzer
2025-07-25 16:40:00,086 - INFO - energy-analyzer succeeded: Dummy processed /data/output1.json to /data/output2.json
2025-07-25 16:40:00,086 - INFO - [gRPC] Executing report-generator
2025-07-25 16:40:00,086 - INFO - report-generator succeeded: Dummy processed /data/output2.json to /data/energy_report.csv
2025-07-25 16:40:00,086 - INFO - gRPC pipeline completed.
2025-08-19 10:27:40,754 - ERROR - Unhandled error in orchestrator
Traceback (most recent call last):
  File "/Users/legion/Documents/AI-Effect-W3.2/src/orchestrator/grpc_main.py", line 37, in <module>
    execute_workflow(config["containers"])
  File "/Users/legion/Documents/AI-Effect-W3.2/src/orchestrator/grpc_executor.py", line 31, in execute_workflow
    raise ValueError("Missing 'start_node' in config")
ValueError: Missing 'start_node' in config
2025-08-19 10:30:13,006 - INFO - [gRPC] Connecting to energy-generator at localhost:50051
2025-08-19 10:30:13,013 - ERROR - gRPC error for energy-generator: failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50051: Failed to connect to remote host: connect: Connection refused (61)
2025-08-19 10:30:13,013 - WARNING - gRPC pipeline stopped due to an error.
